%% SCRIPT_primaryProcessing
%
% Calls the pupil analysis pre-processing pipeline for LDOG sesson data. It
% is useful to define mask boxes for the glint and pupil. Use this code to
% do so:
%{
	maskBounds = defineCropMask(grayVideoName,'startFrame',10);
%}


%% Universal parameters
% Get the DropBox base directory
dropboxBaseDir = getpref('pupilLDOGAnalysis','dropboxBaseDir');

% set common path params
pathParams.dataSourceDirRoot = fullfile(dropboxBaseDir,'LDOG_data');
pathParams.dataOutputDirRoot = fullfile(dropboxBaseDir,'LDOG_processing');
pathParams.Approach = 'OLApproach_TrialSequenceMR';
pathParams.Protocol = 'MRFlickerLDOG';

% Set parameters common to all analyses from this project
universalKeyValues = {...
    'nWorkers',2,...
    'intrinsicCameraMatrix',[2627.0 0 338.1; 0 2628.1 246.2; 0 0 1],...
    'radialDistortionVector',[-0.3517 3.5353],...
    'eyeLaterality','left',...
    'spectralDomain','nir', ...
    'verbose',true, ...
    'audioTrackSync', true, ...
    'checkCountTRs', 1, ...
    'useParallel',true,...
    };



%% Session parameters

% Params
pathParams.Subject = 'N292';
pathParams.Date = '2020-03-05';
pathParams.Session = 'session_3';

% Key-values for this session
sessionKeyValues = {...
    'glintFrameMask',[222   215   170   330],...
    'glintGammaCorrection',1,...
    'glintThreshold',0.5,...
    'pupilFrameMask',[186   124    69   239],...
    'pupilRange',[42 51],...
    'pupilCircleThresh',0.0180,...
    'glintPatchRadius',40,...
    'candidateThetas',[pi],...
    'ellipseTransparentUB',[640,480,20000,0.5, pi],...
    'cutErrorThreshold',1.5,...
    };

% The names of the videos to process
videoNameStems = {'pupil_LightFLux','pupil_L+S','pupil_RodMel','pupil_LightFLux02','pupil_L+S02','pupil_RodMel02'};

% Call the pipeline
pupilPipeline(pathParams,videoNameStems, universalKeyValues, sessionKeyValues)